### ISSUE TITLE
Libraries incompatibility

### ISSUE THREAD

**Issue by Sanavuth** [Axway-API-Management-Plus/aws-lambda-apim-sdk#1]
Hi,

We are currently using your lib to execute lambdas through API Gateway.
As far as lambda execution is concerned, everything runs smoothly.
However, the API Gateway deployment fails due to the native filter "Send to AWS SQS" that we are using in another API.
In fact, API Gateway 7.5.3 natively delivers aws-java-sdk-1.7.1.jar which contains com.amazonaws.http.AmazonHttpClient.disableStringHostnameVerification.
This method is absent from the lib aws-java-sdk-core-1.11.282.jar therefore an error is thrown.
Do you think something can be done in order to avoid conflicts?

Regards,

Sana

**Comment by rathnapandi** [comment]
Hi Sana, 

I could see two options

1. Add custom classloader through esexplorer. 
2. Build a custom filter / script  for SQS to support new AWS SDK

Thanks
Rathna

**Comment by rathnapandi** [comment]
Updated libraries to AWS SDK 1.11.564
